# Generated by Django 3.2.15 on 2024-04-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20221106_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedIn_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
